name: Build
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - run: pip install PyInstaller PyQt5
      - run: pyinstaller --onefile --windowed your_script.py
      - uses: actions/upload-artifact@v3
        with:
          name: MyApp_${{ matrix.os }}
          path: dist/