name: Build PyQt5 Executables

on: push

# on:
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "img/logo-96.ico" --add-data "img/;img/"  YGOProxyPrinter_UI.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-windows
          path: dist\YGOProxyPrinter_UI.exe

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxcb-xinerama0
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build Linux Binary
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "img/logo-96.ico" --add-data "img/;img/"  YGOProxyPrinter_UI.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-linux
          path: dist/YGOProxyPrinter_UI

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=img/logo-96.ico --add-data=img:img YGOProxyPrinter_UI.py

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-macos
          path: dist/YGOProxyPrinter_UI
