name: Build Executables
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0 libgl1-mesa-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name "MyApp_${{ runner.os }}" \
            --add-data "img/:img/" \
            YGOProxyPrinter_UI.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp_${{ runner.os }}
          path: dist/