name: Build PyQt5 Executables

on:
    push:
        branches: [ master ]
    workflow_dispatch:
        branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      
      # Install Node.js and png2icons
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install png2icons
        run: npm install -g png2icons

      # Convert logo.png to .ico
      - name: Generate Windows .ico icon
        run: |
          png2icons ./img/logo.png ./img/logo -icowe
      
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon "img/logo.ico" --add-data "img/;img/" --splash "img/Splash_screen.png" YGOProxyPrinter_UI.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-windows
          path: dist\YGOProxyPrinter_UI.exe

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.12'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxcb-xinerama0
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      
      # Install Node.js and png2icons
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install png2icons
        run: npm install -g png2icons

      # Convert logo.png to .ico
      - name: Generate .ico icon
        run: |
          png2icons ./img/logo.png ./img/logo -ico
      
      - name: Build Linux Binary
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=img/logo.ico --add-data=img:img --splash "img/Splash_screen.png" YGOProxyPrinter_UI.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-linux
          path: dist/YGOProxyPrinter_UI

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      
      # Install Node.js and png2icons
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install png2icons
        run: npm install -g png2icons

      # Convert logo.png to .icns (macOS icon format)
      - name: Generate macOS .icns icon
        run: |
          png2icons ./img/logo.png ./img/logo -icns

      - name: Build macOS App bundle
        run: |
          pyinstaller --noconfirm --onefile --windowed --icon=img/logo.icns --add-data=img:img --name "YGOProxyPrinter_UI" YGOProxyPrinter_UI.py
      
      # # Package the .app into a ZIP for easier download
      # - name: Package .app for distribution
        # run: |
          # cd dist
          # zip -r YGOProxyPrinter_UI.zip YGOProxyPrinter_UI.app

      # Upload the final .app bundle as an artifact
      - name: Upload macOS Artifact (.app bundle)
        uses: actions/upload-artifact@v4
        with:
          name: YGOProxyPrinter-macos
          path: dist/YGOProxyPrinter_UI.app
          #path: dist/YGOProxyPrinter_UI.zip
